# Generated by Django 2.0.1 on 2018-02-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('point_id', models.IntegerField()),
                ('d1', models.FloatField()),
                ('h', models.FloatField()),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Number')),
            ],
        ),
        migrations.CreateModel(
            name='PointLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField()),
                ('line_id', models.IntegerField()),
                ('d', models.FloatField()),
                ('y', models.FloatField()),
                ('x', models.FloatField()),
                ('h', models.FloatField()),
                ('d0', models.FloatField()),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Number')),
            ],
        ),
    ]
